# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FILE/FPGA/ZYNQ/TEST/OV5640_Nexys_Video_CSDN/OV5640_Nexys_Video_CSDN/HDMI/HDMI.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/FPGA/ZYNQ/TEST/OV5640_Nexys_Video_CSDN/OV5640_Nexys_Video_CSDN/HDMI/HDMI.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/FILE/FPGA/ZYNQ/TEST/OV5640_Nexys_Video_CSDN/OV5640_Nexys_Video_CSDN/HDMI/HDMI.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/FPGA/ZYNQ/TEST/OV5640_Nexys_Video_CSDN/OV5640_Nexys_Video_CSDN/HDMI/HDMI.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
