# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FILE/FPGA/ZYNQ/TEST/CH04_OV5640_DEMO/OV5640_TS_DATA/MIG_OV_PRG/MIG_OV_PRG.srcs/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi.xci
# IP: The module: 'clk_wiz_hdmi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/FPGA/ZYNQ/TEST/CH04_OV5640_DEMO/OV5640_TS_DATA/MIG_OV_PRG/MIG_OV_PRG.srcs/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_hdmi'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/TEST/CH04_OV5640_DEMO/OV5640_TS_DATA/MIG_OV_PRG/MIG_OV_PRG.srcs/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/TEST/CH04_OV5640_DEMO/OV5640_TS_DATA/MIG_OV_PRG/MIG_OV_PRG.srcs/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/FILE/FPGA/ZYNQ/TEST/CH04_OV5640_DEMO/OV5640_TS_DATA/MIG_OV_PRG/MIG_OV_PRG.srcs/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi.xci
# IP: The module: 'clk_wiz_hdmi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/FPGA/ZYNQ/TEST/CH04_OV5640_DEMO/OV5640_TS_DATA/MIG_OV_PRG/MIG_OV_PRG.srcs/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/TEST/CH04_OV5640_DEMO/OV5640_TS_DATA/MIG_OV_PRG/MIG_OV_PRG.srcs/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/TEST/CH04_OV5640_DEMO/OV5640_TS_DATA/MIG_OV_PRG/MIG_OV_PRG.srcs/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
