# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/FILE/Xilinx/Miz7035/My_ip_lib/rgb2dvi_1_1/rgb2dvi_1.xci
# IP: The module: 'rgb2dvi_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/rgb2dvi_1_1/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/rgb2dvi_1_1/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/rgb2dvi_1_1/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/FILE/Xilinx/Miz7035/My_ip_lib/rgb2dvi_1_1/rgb2dvi_1.xci
# IP: The module: 'rgb2dvi_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/rgb2dvi_1_1/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/rgb2dvi_1_1/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/rgb2dvi_1_1/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
