webtalk_init -webtalk_dir F:/BaiduNetdiskDownload/S07_CH09/mig_7series_0_ex.sim/sim_1/behav/xsim.dir/sim_tb_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 29 00:35:36 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1733598" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ecaade6ac8d7548586407d2edac25bf7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ff983edbd7814f3ab5aa1070f3862d3f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100365990370 fs" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1112.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116768_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2621507981 -regid "" -xml F:/BaiduNetdiskDownload/S07_CH09/mig_7series_0_ex.sim/sim_1/behav/xsim.dir/sim_tb_top_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/BaiduNetdiskDownload/S07_CH09/mig_7series_0_ex.sim/sim_1/behav/xsim.dir/sim_tb_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/BaiduNetdiskDownload/S07_CH09/mig_7series_0_ex.sim/sim_1/behav/xsim.dir/sim_tb_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
