# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/FILE/Xilinx/Miz7035/My_ip_lib/XILSQRT/XILSQRT.xci
# IP: The module: 'XILSQRT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/XILSQRT/XILSQRT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XILSQRT'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/FILE/Xilinx/Miz7035/My_ip_lib/XILSQRT/XILSQRT.xci
# IP: The module: 'XILSQRT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/XILSQRT/XILSQRT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XILSQRT'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
