# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/FILE/Xilinx/Miz7035/My_ip_lib/Line_Shift_RAM_8Bit/Line_Shift_RAM_8Bit.xci
# IP: The module: 'Line_Shift_RAM_8Bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/Line_Shift_RAM_8Bit/Line_Shift_RAM_8Bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Line_Shift_RAM_8Bit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/FILE/Xilinx/Miz7035/My_ip_lib/Line_Shift_RAM_8Bit/Line_Shift_RAM_8Bit.xci
# IP: The module: 'Line_Shift_RAM_8Bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/Line_Shift_RAM_8Bit/Line_Shift_RAM_8Bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Line_Shift_RAM_8Bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
