# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/FILE/Xilinx/Miz7035/My_ip_lib/clk_wiz_1_3/clk_wiz_1.xci
# IP: The module: 'clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/clk_wiz_1_3/clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/clk_wiz_1_3/clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/clk_wiz_1_3/clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/FILE/Xilinx/Miz7035/My_ip_lib/clk_wiz_1_3/clk_wiz_1.xci
# IP: The module: 'clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/clk_wiz_1_3/clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/clk_wiz_1_3/clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/Xilinx/Miz7035/My_ip_lib/clk_wiz_1_3/clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
